### ISSUE TITLE
Scaling ratio related display problems on windows

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3604]
**Describe the bug**
Following #3596 new problems appeared on windows with a scaling of 150% (which worked almost perfectly before):
 - the gaml reference popup is displayed on the wrong screen (not even my main screen):
 ![image](https://user-images.githubusercontent.com/6374469/216869693-35678c5a-4358-4df0-8928-47e4efaee07f.png)
 - all the small buttons to interact with the simulation look like they were 16x16px and scaled up:
 ![image](https://user-images.githubusercontent.com/6374469/216869617-f6996d03-e0e1-4870-85ff-a40b0119a312.png)
 - at startup, after asking for workspace the splash screen "moves":
 ![image](https://user-images.githubusercontent.com/6374469/216871055-10e9779e-dfd9-431c-8feb-ef1699c6155b.png)
 - 2d display do not fill the whole available space
 ![image](https://user-images.githubusercontent.com/6374469/216871857-a90982e8-709b-43ab-9d1b-8d9e73736c84.png)

With 175% I have the same problems plus those lines everywhere:
 ![image](https://user-images.githubusercontent.com/6374469/216869141-31e5976c-edd4-47b0-a00a-c8f73bc67a33.png)
They can disappear sometime when scrolling

My configuration is:
Windows 11
screens: 
 - 1 hidpi (2k for 15") at 1920x1200px (16:10) and 150% scaling
 - 1 normal at 1920x1080px (16:9) and 100% scaling

**Comment by lesquoyb** [comment]
following the changes in configuration recommended in #3308, there's only two remaining issues from the original list:
 - the resolution of some buttons are still not correct
 - the splash screen changes resolution after picking the workspace

**Comment by AlexisDrogoul** [comment]
For the first point, I am afraid we will need to move to the solution presented in https://www.slideshare.net/eclipsedayindia/scaling-eclipse-on-hidpi-monitors-niraj-modi (from slide 17). That will require some work ! But guarantee the independence of the icons in terms of resolution. 
For the second point, it is surprising that it is supposed to be "solved" in this report (https://bugs.eclipse.org/bugs/show_bug.cgi?id=527297): probably the dynamic change of handling the scaling is the cause of that. I will try to put it very early in the form of `-Dswt.autoScale=exact` to see if it changes something. If it is the case, then we will probably need to get rid of the GAMA specific flag (`-Duse_precise_scaling`).

**Comment by AlexisDrogoul** [comment]
The second issue (splash screen changing resolution) should be fixed by now, and not show up anymore on the release version. The dev version of GAMA (from Eclipse) will however still exhibit it normally, and there is nothing we can do about this !

**Comment by lesquoyb** [comment]
I tried the latest release and the splash screen problem is still present:
![image](https://user-images.githubusercontent.com/6374469/219999908-e41c27d5-427f-419c-bf56-226a490ea252.png)

**Comment by AlexisDrogoul** [comment]
Can you verify that the flags are ok on the release and if the problem is present in all resolutions / zoom factors ?

**Comment by lesquoyb** [comment]
I have the `autoScale` flag set to `exact`. Here is the complete ini:
```
-vm
./jdk/bin/javaw
-startup
plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.win32.win32.x86_64_1.2.700.v20221108-1024
-data
@noDefault
--launcher.defaultAction
openFile
-vmargs
-server
-XX:+UseG1GC
-XX:+UseStringDeduplication
-Dorg.eclipse.swt.graphics.Resource.reportNonDisposed=false
-Xms4096m
-Xmx4096m
-Xss128m
-Xmn1024m
-XX:+UseAdaptiveSizePolicy
-XX:+OptimizeStringConcat
-Dosgi.locking=none
-Dosgi.checkConfiguration=false
-Declipse.log.level=ERROR
-Dorg.eclipse.ecf.provider.filetransfer.retrieve.retryAttempts=10
-Dorg.eclipse.ecf.provider.filetransfer.retrieve.closeTimeout=6000
-Dorg.eclipse.ecf.provider.filetransfer.retrieve.readTimeout=6000
-Denable_logging=true
-Denable_debug=true
-Duse_global_preference_store=true
-Dswt.autoScale=exact
-Dread_only=false
-Duse_old_tabs=true
-Duse_legacy_drawers=false
-Duse_delayed_resize=false
-Duse_native_opengl_window=true
--add-opens=java.base/java.lang=ALL-UNNAMED
--add-exports=java.base/java.lang=ALL-UNNAMED
--add-exports=java.desktop/sun.awt=ALL-UNNAMED
--add-exports=java.desktop/sun.java2d=ALL-UNNAMED
--add-exports=java.desktop/sun.awt.image=ALL-UNNAMED
-Dfile.encoding=UTF-8
```
If I switch `autoScale` to true there's no more splash screen issue, but we can't do that because we would be coming back to the problems we had with the `user_location`

**Comment by lesquoyb** [comment]
**Update following the recent commits related to icons**
most icons have been improved and overall it looks way better now. There are still a few icons that may have been missed though:
  *  in the models explorer view, all the icons are still the same as before:
![image](https://user-images.githubusercontent.com/6374469/222943429-b1798f39-8563-423c-9c08-dfcf1b654a89.png)
  * in the code editor, the + and - buttons to toggle code blocks as well as the info icon
![image](https://user-images.githubusercontent.com/6374469/222943500-e7776382-260e-4f97-a07a-06b1c491aab5.png)
  * the greyed arrows in the top bar of the code editor 
![image](https://user-images.githubusercontent.com/6374469/222943520-a4fbb933-1f63-4838-88a0-8a6d012cc534.png)
  * tabs of the code editor 
![image](https://user-images.githubusercontent.com/6374469/222943555-82dee92d-9d1a-401b-bb3c-c578095c8870.png)
  * the top left icon of gama windows 
![image](https://user-images.githubusercontent.com/6374469/222943581-302263cf-5fff-4819-9865-047c4aa308bd.png)
  * the info icon at the bottom left corner of the new model/project/experiment window (btw about that window: there is no window title and the bold text at the top has rendering issues)
![image](https://user-images.githubusercontent.com/6374469/222943627-e6c3007d-ab3e-4d54-bead-3b95ba620b8d.png)
  * the icons in the "Select a wizard" window (in File -> New -> Other...) 
![image](https://user-images.githubusercontent.com/6374469/222944044-af506afa-9c3a-476b-9eaf-8250474047cc.png)
  * the undo and redo icons in the edit menu 
![image](https://user-images.githubusercontent.com/6374469/222944121-325c85bd-db03-49f2-979f-80280e55ab98.png)
  * the icons in the general section of the show view window (Views -> other... -> show view -> other...)
![image](https://user-images.githubusercontent.com/6374469/222944229-a95f13c5-2078-4c30-bda5-e1bbde2aff26.png)
  * the gama icon in the help menu 
![image](https://user-images.githubusercontent.com/6374469/222944356-57163f75-cc8e-43df-90be-52f9deab1821.png)
  * all the icons in the about gama window 
![image](https://user-images.githubusercontent.com/6374469/222944414-31c776b8-0f99-4421-947e-70f10b1f70a8.png)
  * the detailed icon in the "about gama feature" windows 
![image](https://user-images.githubusercontent.com/6374469/222944567-3d291008-9baf-48e8-9d94-e3e301afe625.png)
  * the info hint in the install plugin window 
![image](https://user-images.githubusercontent.com/6374469/222944700-a6bc4712-991d-4416-be1a-a9a2d0c2273e.png)
  * the info circle in the plugin list of the install plugin window 
![image](https://user-images.githubusercontent.com/6374469/222944753-0decdc12-15a0-477c-9e63-e055867a609b.png)
  * the import/export icons as well as the arrows and option icons in the preference window 
![image](https://user-images.githubusercontent.com/6374469/222944854-acc14843-a5d1-4905-9ada-8bd86aec2964.png)
  * the greyed revert to original value icon for experiment parameters 
![image](https://user-images.githubusercontent.com/6374469/222944962-ef5bc192-eb33-4ebc-b276-e6ab09cb638f.png)
  * the remove all finished operations, and tab icon of the progress tab 
![image](https://user-images.githubusercontent.com/6374469/222945027-5a953955-7454-44fd-becf-cd67a3e552aa.png)
  * the filters icon in the validation view 
![image](https://user-images.githubusercontent.com/6374469/222945062-c58ccb07-64f4-414b-af12-c23ab907f4f8.png)
  * I don't know if it's related but the red icons mentioned in #3630 are still not replaced

**Comment by AlexisDrogoul** [comment]
The different icons which are managed directly by GAMA should be ok (or will be ok soon: some will take a bit of time to process like the ones in the "About" window). This leaves : 
1. the ones in the navigator and/or editor tabs, which preoccupy me a bit, as we have no way to manage them directly. I am a bit at loss here, since all the components (and overlays) are correctly produced in 3 sizes ... 
2. the ones managed by Eclipse (easy to recognise visually), and for which I have absolutely no clue why it doesn't work like in Eclipse. It should, by all means, unless we forgot some configuration files or properties ? 

Regarding the 2nd one (both may be linked by the way -- which I hope !), there still exists tons of issues on Eclipse regarding the behaviour with unusual scaling (like 150%) and multiple monitors (e.g. https://bugs.eclipse.org/bugs/show_bug.cgi?id=563923 or https://bugs.eclipse.org/bugs/show_bug.cgi?id=558837). Can you conduct tests **without** connecting the two different monitors ? Thanks !

**Comment by lesquoyb** [comment]
About the computer I did the previous review: it's my other laptop which is a "normal" one, only one screen, not hidpi screen, and the scaling factor was the recommended 150% (not a strange 175% or 225%), so I think we can assume it's not related to the hardware or a funky setup.

So apart from the eclipse and navigator/editor's icons, what changed/didn't change:
  * the gama main icon is now a red square as mentioned in #3654
  * the info icon in the editor is fixed
  * the greyed arrows and parameter icons are fixed
  * the validation view icons turned into question marks 
![image](https://user-images.githubusercontent.com/6374469/223611300-e74a1215-0673-4840-9530-6bdb5d13381d.png)
  * the icon of the display when running an experiment has a black background ![image](https://user-images.githubusercontent.com/6374469/223611104-f1fc9fc2-7714-492d-a19b-8fda2cc5f3e2.png)
  * the about gama window somehow got worse ![image](https://user-images.githubusercontent.com/6374469/223622236-be5ea7c9-1606-4e9e-8bf3-c8b0bc086f2c.png)

**Comment by AlexisDrogoul** [comment]
Is it on the release or in Eclipse ? If in Eclipse, remember to synchronise the product with the run configurations (or to launch from the product).

**Comment by lesquoyb** [comment]
It is both in eclipse and the release. I tried synchronizing but no difference

**Comment by lesquoyb** [comment]
If it can help figuring out where does the problem lie: the initial gama icon for the splash screen works normally, but the workspace selection wizard has a broken icon and once the workspace selected, the icon of the splash-screen becomes a red square too
![image](https://user-images.githubusercontent.com/6374469/223673811-defea0d6-ff77-4e35-8e53-3107110ea398.png)
here for example you can see both the proper icon for the splash screen and the broken one for the wizard

**Comment by lesquoyb** [comment]
**Update about the fix of the red icon**
* In the latest release, though the icon is now found, there's a difference between the icon of the splash screen and the one of the workspace wizard (and later of gama):
 ![image](https://user-images.githubusercontent.com/6374469/224536795-cd30e842-5a04-43cb-a7a3-a9e22fc8c4eb.png)
the bigger one is the one the workspace wizard.
It is also the case with the icon of "about gama" in the help menu that doesn't seem to have been scaled:
![image](https://user-images.githubusercontent.com/6374469/224536955-8bc42429-3bae-4080-acba-0626e6d00b36.png)

* In addition I noticed that the icon to pick a background color in the image view is also a bit strange (in the same that the display tab icon is): ![image](https://user-images.githubusercontent.com/6374469/224536914-4351eda5-7df4-4810-a9dd-9f6cb37fd938.png)

**Comment by AlexisDrogoul** [comment]
Regarding the images for picking up colours, display tabs or simulation (in the "Agents" menu), I obtain those on my computer (masOS):

![Image 2023-03-12 17-27-55](https://user-images.githubusercontent.com/579256/224538896-e058d224-d58d-4552-891a-284fc3ecb2b8.png)
![Image 2023-03-12 17-31-30](https://user-images.githubusercontent.com/579256/224539054-afa5d854-4a2a-49ab-b6b2-81508ce0f4cc.png)
![Image 2023-03-12 17-32-48](https://user-images.githubusercontent.com/579256/224539125-7c8d6ea1-6e8a-4e10-b836-50f74264ee6b.png)

I have just committed a small change that might help on windows to recover the transparency that seems absent. Can you try it ?

**Comment by lesquoyb** [comment]
It didn't change anything, so far the icons that have this problem are:
 * display tab icon ![image](https://user-images.githubusercontent.com/6374469/224600720-3541447c-8450-4227-a610-9aec0084656e.png)
 * simulation menu icon ![image](https://user-images.githubusercontent.com/6374469/224600802-57a9b858-e0d6-4151-9793-0a4926bc1f06.png)
 * background color/ set fill color/set line color icons ![image](https://user-images.githubusercontent.com/6374469/224600908-71b5d718-503f-4121-b30f-0bd330922e0f.png)
   * When clicking on one of those we can see all the possible icons. They all suffer from the same problem, apart from the black one, but this one has no color in the center: 
![image](https://user-images.githubusercontent.com/6374469/224602370-7d811587-fa79-4061-800f-ddf42b4bc790.png)

**Comment by RoiArthurB** [comment]
@AlexisDrogoul since your last commit, every icons are working well, except the one in Help > About GAMA :/ 

![image](https://user-images.githubusercontent.com/16764085/224648558-c5116dea-c743-401c-832a-f173fc11892a.png)

**Comment by lesquoyb** [comment]
To summarize what's left as of now:
  * The about gama icon mentioned by Arthur ![image](https://user-images.githubusercontent.com/16764085/224648558-c5116dea-c743-401c-832a-f173fc11892a.png)
  * The extensions icons in the about gama window: ![image](https://user-images.githubusercontent.com/6374469/224885860-b55a661b-3db7-4d57-9c02-0493c59c90ec.png)
  * Those same icons in the About Gama Features window ![image](https://user-images.githubusercontent.com/6374469/224885969-b21f8b8e-9474-4879-b518-79b892e0e7cb.png)
  * The eclipse editor/navigator/menu icons, but I guess we can't do anything about it
  * The splash screen once the workspace is selected is zoomed (I don't think it's really important as it's only a few seconds, but I'm referencing it in order to be complete) ![image](https://user-images.githubusercontent.com/6374469/224887019-f2de7cfa-c7e8-4c92-82b5-debb8725d95c.png)

And that's it!

**Comment by AlexisDrogoul** [comment]
@lesquoyb Please test the latest commit. In case it doesn't work better, could you try coming back two commits earlier (https://github.com/gama-platform/gama/commit/23760b80ce317c751917e37b27459c2b954ba926) and test as well ? Just in case something is  related to loading the icons a bit too early (a remark you made yesterday made me think about this: on Windows, we have this "zooming effect" on the splash, which indicates a change in resolution during the launch, something that does not happen on macOS).

**Comment by lesquoyb** [comment]
With the latest commit icons cannot be found:
```
java.io.FileNotFoundException: /icons/window/icon256.png
	at org.eclipse.osgi.storage.url.bundleentry.Handler.findBundleEntry(Handler.java:55)
	at org.eclipse.osgi.storage.url.BundleResourceHandler.openConnection(BundleResourceHandler.java:182)
	at java.base/java.net.URL.openConnection(URL.java:1094)
	at org.eclipse.core.internal.boot.PlatformURLConnection.connect(PlatformURLConnection.java:115)
	at org.eclipse.core.internal.boot.PlatformURLConnection.getURLAsLocal(PlatformURLConnection.java:240)
	at org.eclipse.core.internal.runtime.PlatformURLConverter.toFileURL(PlatformURLConverter.java:37)
	at org.eclipse.core.runtime.FileLocator.toFileURL(FileLocator.java:266)
	at org.eclipse.jface.resource.URLImageDescriptor.getFilePath(URLImageDescriptor.java:213)
	at org.eclipse.jface.resource.URLImageDescriptor.getImagePath(URLImageDescriptor.java:309)
	at org.eclipse.swt.internal.DPIUtil.validateAndGetImagePathAtZoom(DPIUtil.java:426)
	at org.eclipse.swt.graphics.Image.<init>(Image.java:672)
	at org.eclipse.jface.resource.URLImageDescriptor.createImage(URLImageDescriptor.java:241)
	at org.eclipse.jface.resource.ImageDescriptor.createImage(ImageDescriptor.java:290)
	at org.eclipse.jface.resource.ImageDescriptor.createImage(ImageDescriptor.java:268)
	at org.eclipse.ui.internal.Workbench.initializeImages(Workbench.java:1801)
	at org.eclipse.ui.internal.Workbench.createDisplay(Workbench.java:752)
	at org.eclipse.ui.PlatformUI.createDisplay(PlatformUI.java:183)
	at msi.gama.application.Application.configureDisplay(Application.java:171)
	at msi.gama.application.Application.start(Application.java:138)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
```
Given the log in eclipse console, it seems like all the icons in the `window` folder from size 16 to 256 are loaded in parallel of the initialization.

Coming back to https://github.com/gama-platform/gama/commit/23760b80ce317c751917e37b27459c2b954ba926 didn't fix the navigator icons and this error rose during init:
```
java.lang.NullPointerException: Cannot invoke "org.eclipse.equinox.p2.repository.artifact.IFileArtifactRepository.query(org.eclipse.equinox.p2.query.IQuery, org.eclipse.core.runtime.IProgressMonitor)" because "bundlePoolRepository" is null
	at org.eclipse.equinox.internal.p2.ui.KeySigningInfoFactory.getBundlePoolArtficactPGPSigningDetails(KeySigningInfoFactory.java:148)
	at org.eclipse.equinox.internal.p2.ui.KeySigningInfoFactory$1.<init>(KeySigningInfoFactory.java:43)
	at org.eclipse.equinox.internal.p2.ui.KeySigningInfoFactory.getAdapter(KeySigningInfoFactory.java:42)
	at org.eclipse.core.internal.adapter.AdapterFactoryProxy.lambda$5(AdapterFactoryProxy.java:111)
	at java.base/java.util.Optional.map(Optional.java:260)
	at org.eclipse.core.internal.adapter.AdapterFactoryProxy.getAdapter(AdapterFactoryProxy.java:111)
	at org.eclipse.core.internal.runtime.AdapterManager.lambda$7(AdapterManager.java:248)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	at org.eclipse.core.internal.runtime.AdapterManager.getAdapter(AdapterManager.java:261)
	at org.eclipse.ui.internal.about.AboutPluginsPage.lambda$0(AboutPluginsPage.java:334)
	at org.eclipse.core.runtime.jobs.Job$2.run(Job.java:187)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by AlexisDrogoul** [comment]
Hello, if you run from Eclipse, please make sure you re-synchronize the product.

**Comment by lesquoyb** [comment]
You are right, I synchronized before the first try but not after checkingout to the old commit. Though it didn't change anything apart from the error message not showing up in the eclipse console.

Also, I feel like you were right about the fact that it may come from images composed with other images:
![image](https://user-images.githubusercontent.com/6374469/225195139-cbc32dcf-e491-4760-9bad-8c55de0f1485.png)
The icon for `includes ` is not blurry at all and it's the only one that is not composed of multiple images

**Comment by AlexisDrogoul** [comment]
And do you face the same issue in Eclipse ?

**Comment by lesquoyb** [comment]
Oh actually yes, they are blurry too in eclipse navigator. It was hard to see because they are so tiny, but I just did the test with taking a snapshot of the same area with 150% scaling and 100%, and some 150% are pixelated too.
here with 150% scaling: 
![image](https://user-images.githubusercontent.com/6374469/225243555-2bcb4e29-56ce-4ba9-ace1-748e0c491e7e.png)
and here with 100% scaling:
![image](https://user-images.githubusercontent.com/6374469/225244269-d9485f2c-1809-4e1f-9cc5-aad72ec6b093.png)
What is strange is that in this case, it's not the images composed of multiple layers that are blurry, but the arrows

**Comment by lesquoyb** [comment]
something I just noticed now, the zoom is actually the zoom of the main monitor. If I want to run gama on my second monitor it will always open on my main screen first, then move to my second screen. The consequences are that many icons are broken, particularly the eclipse ones:
![image](https://user-images.githubusercontent.com/6374469/225268508-14927f1b-2b60-4c28-82ef-ea5580ac6287.png)

Eclipse loads the same way (splash screen on the main screen then moves by itself to the correct monitor), but it does seem to cause any problem.

The scaling ratio of my second screen is 100% and the one of my main screen is 150%. If we ignore the icons that completly break (menu icons only from what I've seen so far, the aspect is the one of 150% scaling, which overall looks ok:
![image](https://user-images.githubusercontent.com/6374469/225270021-62a3858b-45cb-4e21-a8d4-75cbf92cfd21.png)

**Comment by lesquoyb** [comment]
## Two monitors bug
That bug with the two monitors with different scaling ratios actually goes way deeper, it also breaks the java2d displays, here for example is the model `Clean Line Network.gaml` run on my second monitor with a 100% while my main monitor has a 200% scaling:
![image](https://user-images.githubusercontent.com/6374469/225567212-832e94ff-6e17-4f57-85cb-8a8a248b831d.png)

Those bugs are not present in the 1.8.2-RC2 release.

Watching the code we use, I noticed that the `DPIUtil.getDeviceZoom()` we use in the code only returns the main monitor scaling, not the scaling of the current monitor, which could be one of the reason for those bugs.

## Navigator icons
Getting back to the problem with navigator icons, it turns out that with a 200% scaling, the navigator icons are not pixelated at all, so it only appears with 150%/175% etc.

## The transparent icons bug
I don't know how, but that bug came back: ![image](https://user-images.githubusercontent.com/6374469/225576712-78be55dd-b22f-4a2d-a5cd-6aa09647f723.png)

## Some icons are missing:
in the eclipse console there are a few errors due to missing icons:
```
java.io.FileNotFoundException: /icons/view.interactive2.png
	at org.eclipse.osgi.storage.url.bundleentry.Handler.findBundleEntry(Handler.java:55)
	at org.eclipse.osgi.storage.url.BundleResourceHandler.openConnection(BundleResourceHandler.java:182)
	at java.base/java.net.URL.openConnection(URL.java:1094)
	at org.eclipse.core.internal.boot.PlatformURLConnection.connect(PlatformURLConnection.java:115)
	at org.eclipse.core.internal.boot.PlatformURLConnection.getURLAsLocal(PlatformURLConnection.java:240)
	at org.eclipse.core.internal.runtime.PlatformURLConverter.toFileURL(PlatformURLConverter.java:37)
	at org.eclipse.core.runtime.FileLocator.toFileURL(FileLocator.java:266)
	at org.eclipse.jface.resource.URLImageDescriptor.getFilePath(URLImageDescriptor.java:213)
	at org.eclipse.jface.resource.URLImageDescriptor.getImagePath(URLImageDescriptor.java:309)
	at org.eclipse.swt.internal.DPIUtil.validateAndGetImagePathAtZoom(DPIUtil.java:426)
	at org.eclipse.swt.graphics.Image.<init>(Image.java:672)
	at org.eclipse.jface.resource.URLImageDescriptor.createImage(URLImageDescriptor.java:241)
	at org.eclipse.jface.resource.ImageDescriptor.createResource(ImageDescriptor.java:230)
	at org.eclipse.jface.resource.DeviceResourceManager.allocate(DeviceResourceManager.java:55)
	at org.eclipse.jface.resource.AbstractResourceManager.create(AbstractResourceManager.java:88)
	at org.eclipse.jface.resource.LazyResourceManager.create(LazyResourceManager.java:103)
	at org.eclipse.jface.resource.ResourceManager.createImageWithDefault(ResourceManager.java:195)
	at org.eclipse.jface.resource.ImageRegistry.get(ImageRegistry.java:206)
	at org.eclipse.e4.ui.workbench.renderers.swt.SWTPartRenderer.getImageFromURI(SWTPartRenderer.java:228)
	at org.eclipse.e4.ui.workbench.renderers.swt.SWTPartRenderer.getImage(SWTPartRenderer.java:238)
	at org.eclipse.e4.ui.workbench.renderers.swt.StackRenderer.createTab(StackRenderer.java:794)
	at org.eclipse.e4.ui.workbench.renderers.swt.LazyStackRenderer.processContents(LazyStackRenderer.java:205)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:673)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:763)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:728)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:712)
	at org.eclipse.e4.ui.workbench.renderers.swt.SWTPartRenderer.processContents(SWTPartRenderer.java:72)
	at org.eclipse.e4.ui.workbench.renderers.swt.SashRenderer.processContents(SashRenderer.java:150)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:673)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:763)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:728)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:712)
	at org.eclipse.e4.ui.workbench.renderers.swt.SWTPartRenderer.processContents(SWTPartRenderer.java:72)
	at org.eclipse.e4.ui.workbench.renderers.swt.SashRenderer.processContents(SashRenderer.java:150)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:673)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:763)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:728)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:712)
	at org.eclipse.e4.ui.workbench.renderers.swt.SWTPartRenderer.processContents(SWTPartRenderer.java:72)
	at org.eclipse.e4.ui.workbench.renderers.swt.PerspectiveRenderer.processContents(PerspectiveRenderer.java:51)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:673)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:763)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:728)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:712)
	at org.eclipse.e4.ui.workbench.renderers.swt.PerspectiveStackRenderer.showTab(PerspectiveStackRenderer.java:82)
	at org.eclipse.e4.ui.workbench.renderers.swt.LazyStackRenderer.postProcess(LazyStackRenderer.java:116)
	at org.eclipse.e4.ui.workbench.renderers.swt.PerspectiveStackRenderer.postProcess(PerspectiveStackRenderer.java:64)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:677)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:763)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:728)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:712)
	at org.eclipse.e4.ui.workbench.renderers.swt.SWTPartRenderer.processContents(SWTPartRenderer.java:72)
	at org.eclipse.e4.ui.workbench.renderers.swt.SashRenderer.processContents(SashRenderer.java:150)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:673)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:763)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:728)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:712)
	at org.eclipse.e4.ui.workbench.renderers.swt.SWTPartRenderer.processContents(SWTPartRenderer.java:72)
	at org.eclipse.e4.ui.workbench.renderers.swt.WBWRenderer.processContents(WBWRenderer.java:658)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:673)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:763)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:728)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:712)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1083)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at msi.gama.application.Application.start(Application.java:148)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
```

**Comment by AlexisDrogoul** [comment]
Hi,

I propose to close this issue and open one for each of the different problems listed above and the previous ones that are not fixed. Right now, it is a bit too much to handle at once and there is no easy way to link commits with the specific items. 

Thanks ! 

Alexis

PS: as a side note, if the icons with black border have reappeared or if you have this error, it means you are not running the right version of GAMA. Can you check ?

**Comment by lesquoyb** [comment]
I think I transformed all the sub-problems into proper issues, so let's close it
